# Generated by Django 4.2.10 on 2024-03-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_vacancy', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('work_schedule', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=100)),
                ('languages', models.TextField()),
                ('skills', models.TextField()),
                ('link', models.TextField()),
                ('source', models.TextField(default='https://joblab.kz/search_vacancy.php?r=vac&srprofecy=&srcity=&srcategory=16')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.TextField()),
                ('position', models.TextField()),
                ('company', models.TextField()),
                ('responsibilities', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='scrap_vacancy.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField()),
                ('graduated_year', models.TextField()),
                ('university', models.TextField()),
                ('profession', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='scrap_vacancy.resumes')),
            ],
        ),
    ]
